# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies (ignoring prepare scripts, if any)
RUN npm install --ignore-scripts

# Copy all source files
COPY . ./

# Build the project
RUN npm run build

# Expose port if needed (MCP typically runs via stdio, so not needed here)

# Start the MCP server
CMD ["node", "build/index.js"]
